### ISSUE TITLE
crash on world creation

### ISSUE THREAD

**Issue by Xplodin** [igentuman/NuclearCraft-Neoteric#100]
https://gist.github.com/Xplodin/027c517767458b1969762d9130922f4e

version: 1.19.2 - 43.3.9 - 1.0.4

**Comment by HeatherComputer** [comment]
All registry names, resource locations etc need to be lowercase alphanumerical., with no spaces. Underscores are allowed, but other than that they HAVE to be lowercase alphanumerical. 

So there's your fix igentuman

**Comment by igentuman** [comment]
> All registry names, resource locations etc need to be lowercase alphanumerical., with no spaces. Underscores are allowed, but other than that they HAVE to be lowercase alphanumerical.
> 
> So there's your fix igentuman

yes i know. It should use item registry code, but for some reason it doesn't work. And i can't reproduce this issue.

**Comment by igentuman** [comment]
@Xplodin please checkout this build https://github.com/igentuman/NuclearCraft-Neoteric/actions/runs/9015489541

**Comment by Xplodin** [comment]
new crash: 
https://gist.github.com/Xplodin/577a00d8a01e88b305602ab1cfcd19d9

**Comment by HeatherComputer** [comment]
Replace the colon with an underscore if you're copying registry names like that.

Though, why are you duplicating all the recipes like that?

**Comment by Xplodin** [comment]
> Replace the colon with an underscore if you're copying registry names like that.
> 
> Though, why are you duplicating all the recipes like that?

I did add "alltheores" as a mod priority for ores into the materials.toml config if that helps or hinders anything.
I put it as the first priority.

Am unsure if this is me at fault or not.

**Comment by HeatherComputer** [comment]
> I did add "alltheores" as a mod priority for ores into the materials.toml config if that helps or hinders anything.
> I put it as the first priority.
> 
> Am unsure if this is me at fault or not. 


This is entirely an issue with the code, and not with anything you've done. 

Neoteric is directly duplicating all furnace recipes as nuclear furnace recipes, the reason for which is unknown to me, and is doing it in a way that causes crashes.

**Comment by igentuman** [comment]
It's duplicating them on purpose. Nuclear Furnace will and can handle separate recipes. I will check this code

**Comment by igentuman** [comment]
https://github.com/igentuman/NuclearCraft-Neoteric/actions/runs/9043700720

**Comment by blockgoblin31** [comment]
Can you upload the fixed version to curseforge? I'm getting this too in a pack I'm working on.(for 1.19.2)
