### ISSUE TITLE
1.20.1 Leacher has bug

### ISSUE THREAD

**Issue by NHblock714** [igentuman/NuclearCraft-Neoteric#101]
Leacher is unable to input and output correctly, cannot execute the recipe correctly, and there are incorrect building instructions around it
![71$T`5F(%5{Z0P@SDRVK9`R](https://github.com/igentuman/NuclearCraft-Neoteric/assets/94209597/7ddc6361-924d-458b-99df-943c84008dd3)

**Comment by igentuman** [comment]
You need to place pumps in highlighted blocks

**Comment by igentuman** [comment]
Closing as reporter is not responding
