### ISSUE TITLE
[crush][1.20.1] while place "Fluid Infuser" near pipes with water an energy

### ISSUE THREAD

**Issue by tabr** [igentuman/NuclearCraft-Neoteric#103]
beta6 version, also check latest from actions.
java.lang.NullPointerException: Cannot invoke "igentuman.nc.handler.sided.SidedContentHandler$RelativeDirection.ordinal()" because "relativeDirection" is null

[crash-2024-05-12_00.19.06-server.txt](https://github.com/igentuman/NuclearCraft-Neoteric/files/15284349/crash-2024-05-12_00.19.06-server.txt)
![2024-05-12_00-19-05](https://github.com/igentuman/NuclearCraft-Neoteric/assets/683886/16d4d4b7-98eb-47fe-87c8-d328a1860094)

**Comment by igentuman** [comment]
@tabr i was not able to reproduce this issue by any means. But latest commit should cover this problem

**Comment by tabr** [comment]
> @tabr i was not able to reproduce this issue by any means. But latest commit should cover this problem

Yeah, its works, thanks!

**Comment by tabr** [comment]
There was a mekanism gas (oxygen) connection... Both liquid water and oxygen as gas.
