### ISSUE TITLE
[1.20.1][BUG] multitool doen not configures sides

### ISSUE THREAD

**Issue by andrewmateshko** [igentuman/NuclearCraft-Neoteric#106]
tested on barrels, lithium batteries.
RMB, Shift+RMB do nothing.

**Comment by igentuman** [comment]
@andrewmateshko this is on local or server?

**Comment by andrewmateshko** [comment]
> @andrewmateshko this is on local or server?

Server with many other mods:
AdChimneys-1.20.1-10.1.5.1-build.0365.jar
AI-Improvements-1.20-0.5.2.jar
alchemistry-1.20.1-2.3.4.jar
alchemylib-1.20.1-1.0.30.jar
alexsdelight-1.5.jar
alexsmobs-1.22.8.jar
alternate-current-mc1.20-1.8.0-beta.4.jar
appliedcooking-4.0.0.jar
appliedenergistics2-forge-15.2.0.jar
Aquaculture-1.20.1-2.5.1.jar
aquamirae-6.API15.jar
balm-forge-1.20.1-7.2.2.jar
bettervillage-forge-1.20.1-3.2.0.jar
blockui-1.20.1-1.0.156-RELEASE.jar
botarium-forge-1.20.1-2.3.3.jar
buildinggadgets2-1.0.7.jar
car-forge-1.20.1-1.0.17.jar
chemlib-1.20.1-2.0.19.jar
chisels-and-bits-forge-1.4.148.jar
citadel-2.5.4-1.20.1.jar
cloth-config-11.1.118-forge.jar
cofh_core-1.20.1-11.0.0.51.jar
configured-forge-1.20.1-2.2.3.jar
cookingforblockheads-forge-1.20.1-16.0.4.jar
corpse-forge-1.20.1-1.0.12.jar
CraftTweaker-forge-1.20.1-14.0.38.jar
create-1.20.1-0.5.1.f.jar
createaddition-1.20.1-1.2.3.jar
create-new-age-forge-1.20.1-1.1.2.jar
create_power_loader-1.5.0-mc1.20.1.jar
CreateTweaker-forge-1.20.1-4.0.9.jar
cristellib-1.1.5-forge.jar
curios-forge-5.9.0+1.20.1.jar
defaultoptions-forge-1.20-18.0.1.jar
domum_ornamentum-1.20.1-1.0.186-RELEASE-universal.jar
DynamicTrees-1.20.1-1.3.0-BETA2.jar
Dynmap-3.7-beta-4-forge-1.20.jar
EasierSleeping-1.20.1-2.1.3.jar
'Engineers Delight 1.20.1 B.1.3.jar'
FarmersDelight-1.20.1-1.2.4.jar
FastFurnace-1.20.1-8.0.2.jar
FastWorkbench-1.20.1-8.0.4.jar
ForgeEndertech-1.20.1-11.1.3.0-build.0398.jar
ImmersiveEngineering-1.20.1-10.1.0-171.jar
inventorysorter-1.20.1-23.0.1.jar
invtweaks-1.20.1-1.1.0.jar
ironchest-1.20.1-14.4.4.jar
Jade-1.20.1-forge-11.9.1.jar
JadeColonies-1.20.1-1.4.2.jar
jei-1.20.1-forge-15.3.0.4.jar
journeymap-1.20.1-5.9.21-forge.jar
JustEnoughResources-1.20.1-1.4.0.247.jar
kotlinforforge-4.10.0-all.jar
levelhearts-1.20.1-2.4.0.jar
libraryferret-forge-1.20.1-4.0.0.jar
lostcities-1.20-7.1.6.jar
mcw-doors-1.1.0forge-mc1.20.1.jar
Mekanism-1.20.1-10.4.6.20.jar
MekanismGenerators-1.20.1-10.4.6.20.jar
MekanismTools-1.20.1-10.4.6.20.jar
minecolonies-1.20.1-1.1.567-BETA.jar
minecoloniesdynmap-1.20.1-1.0.1-universal.jar
moonlight-1.20-2.11.17-forge.jar
morered-1.20.1-4.0.0.4.jar
MouseTweaks-forge-mc1.20-2.25.jar
nethersdelight-1.20.1-4.0.jar
NuclearCraft-1.20.1-1.0.0-beta.6.jar
obscure_api-15.jar
Patchouli-1.20.1-84-FORGE.jar
Placebo-1.20.1-8.6.1.jar
plane-forge-1.20.1-1.0.8.jar
polymorph-forge-0.49.3+1.20.1.jar
sebastrnlib-4.0.0.jar
skinlayers3d-forge-1.6.4-mc1.20.1.jar
sleep_tight-1.20-1.1.19.jar
sliceanddice-forge-3.2.0.jar
sophisticatedbackpacks-1.20.1-3.20.5.1044.jar
sophisticatedcore-1.20.1-0.6.22.611.jar
soundphysics-forge-1.20.1-1.1.2.jar
Steam_Rails-1.6.4+forge-mc1.20.1.jar
storagedrawers-1.20.1-12.0.3.jar
Structory_Towers_1.20.4_v1.0.6.jar
structurize-1.20.1-1.0.731-RELEASE.jar
Terralith_1.20_v2.5.0.jar
thermal_dynamics-1.20.1-11.0.0.21.jar
thermal_expansion-1.20.1-11.0.0.27.jar
thermal_foundation-1.20.1-11.0.2.64.jar
thermal_innovation-1.20.1-11.0.0.21.jar
thermal_integration-1.20.1-11.0.0.23.jar
thermal_locomotion-1.20.1-11.0.0.17.jar
toofast-1.20-0.4.3.5.jar
ToolBelt-1.20-1.20.0.jar
Towns-and-Towers-1.12-Fabric+Forge.jar
waystones-forge-1.20-14.1.3.jar
wirelessredstone-forge-1.20.1-1.1.2.jar
YungsApi-1.20-Forge-4.0.4.jar
YungsBetterMineshafts-1.20-Forge-4.0.4.jar
YungsBetterOceanMonuments-1.20-Forge-3.0.4.jar
YungsBridges-1.20-Forge-4.0.3.jar
