### ISSUE TITLE
[Suggestion] Custom Moderator blocks

### ISSUE THREAD

**Issue by Xefyr0** [igentuman/NuclearCraft-Neoteric#114]
Currently, Nuclearcraft's Graphite and Beryllium blocks seem to be the only hard-coded moderators.
It would be very much appreciated if fission moderators were defined by the block tag `nuclearcraft:moderators` and so pack developers could add or remove blocks from this tag as needed (For example, GTCEu Graphite and Beryllium blocks) much like how custom coolers can be defined in the config.

**Comment by igentuman** [comment]
Yes. This one is what i planned and planning to do. Right now it's hardcoded because moderators are tile entities. I need to rework that without tile entities

**Comment by igentuman** [comment]
Now you can use forge tag `nuclearcraft:moderators`
