### ISSUE TITLE
Crash on server startup, error on mixing.

### ISSUE THREAD

**Issue by Cosmoros-git** [igentuman/NuclearCraft-Neoteric#123]
1. 1.20.1 1.0.0 rc2
[crash-2024-10-12_18.04.42-server.txt](https://github.com/user-attachments/files/17350717/crash-2024-10-12_18.04.42-server.txt)

Modpack is manufactory 0.9.5; somehow, I got the mod to work when I updated something. Looking into what.

**Comment by Cosmoros-git** [comment]
https://www.curseforge.com/minecraft/mc-mods/disable-villager-trades/files/5033091

This mod makes the game not crash. Villager issues?

**Comment by igentuman** [comment]
I don't see how this related to NC. Mod has nothing to deal with villagers

**Comment by Cosmoros-git** [comment]
The crash happens with your updated version. That mod makes it so the crash does not occur.

**Comment by igentuman** [comment]
Sorry, but NC not touching villagers or trades by any means. Crash log is not pointing to NC code at all.
