### ISSUE TITLE
Crash Nuclear reactor 

### ISSUE THREAD

**Issue by SrNadien** [igentuman/NuclearCraft-Neoteric#124]
NuclearCraft-1.20.1-1.0.0-rc.2.jar

This error happens when you open the nuclear oven and click the (R) button to see the recipes

Crash report:https://mclo.gs/wX8zXWC

I already reported also in jei [jei issue](https://github.com/mezz/JustEnoughItems/issues/3826)

**Comment by igentuman** [comment]
I guess this one fixed already. As i made bunch of fixes in JEI compat features
