### ISSUE TITLE
Nuclear Furnace cloning when fuel in Right slot - 1.20.1 v1.0

### ISSUE THREAD

**Issue by schradieck** [igentuman/NuclearCraft-Neoteric#127]
1.20.1, version 1.0

if you put uranium in the left slot of the Nuclear Furnace, it will smelt 10 of whatever is in the right slot without consuming the input material.
the Furnace works normal with fuel in the Right slot.

Fuel in the Left Slot
https://github.com/user-attachments/assets/6315e018-87f8-4496-aeb9-ce905717ee85

Fuel in the Right Slot
https://github.com/user-attachments/assets/e63f39b4-96ce-4bb7-b4a7-2a2d237b9ae2

**Comment by igentuman** [comment]
Fixed here https://github.com/igentuman/NuclearCraft-Neoteric/commit/30ca195190fd1a0463170f8577b189a51efd557c

**Comment by schradieck** [comment]
WOW that was a fast response, cool then thanks!

**Comment by HeatherComputer** [comment]
The fix was supposedly a full month before the bug report heh
