### ISSUE TITLE
In situ leaching

### ISSUE THREAD

**Issue by igentuman** [igentuman/NuclearCraft-Neoteric#13]
https://en.wikipedia.org/wiki/In_situ_leach

4 pumps in chunk corners
1 leacher at any position in chunk
connect pumps with leacher
leacher input - acid/s
leacher output - slurry

slurry goes to centrifuge to get clean slurry
clean slurry goes to crystallyzer to get raw materials (chunks)

**Comment by igentuman** [comment]
Ore leacher interface will have slot. In this slot player can put a map, ie core sample, or research paper.
1. MAP - leacher will pump all in-world ores in chunk
2. IE core sample - pump resources from IE vein
3. Research Paper - pump resources from NC void vein

Research paper can be accuired from Analyzer machine

**Comment by igentuman** [comment]
Config:
Enable IE compat yes/no
Modify IE veins with NC ores yes/no
Disable NC veins yes/no
NC vein size 40 000 by default
NC vein rarity: range 0 - 10 000; where 0 - every chunk

**Comment by Petrisis** [comment]
How about incorporating two modes of operation? The first mode could involve 'in-world leaching,' which would transform all naturally generated stone and ore within the chunk into a different undesirable stonetype, or even a graveltype, depending on what's suitable. As for the second mode, 'deep leaching,' it could function similarly to the mechanics of IE, with the caveat of potentially requiring slightly more power or additional plumbing for its setup.

I find the overall concept of converting acid into slurry and the arrangement in the corners, along with the flexibility of positioning the leacher, to be highly commendable.
