### ISSUE TITLE
Radiation Removal capped at integer limit

### ISSUE THREAD

**Issue by XCGallivan** [igentuman/NuclearCraft-Neoteric#130]
Currently running release 1.0.5 on Minecraft 1.19.2

By default, the config has RadAway removing 10 Rads, or 10,000,000,000 pRads. With this configuration, the normal "Removes Radiation: [X]" tooltip is not visible (as pictured here), and the radaway has no effect whatsoever. It doesn't even give the intended Radiation Resistance effect.

![image](https://github.com/user-attachments/assets/a06bcdef-7c24-4e05-a4d1-6fb436c8b538)

Through trial and error, I found that the highest value that works is 2147483647, the signed integer limit. The tooltip rounds to the nearest whole Rad at this scale, showing 2 Rads, but checking playerdata it correctly removes the partial units as well. It also gives the Radiation Resistance effect for 1 minute, which I assume is the intended mechanic.

![image](https://github.com/user-attachments/assets/8e58e9db-85c2-4208-abe9-4042f4007fc3)

I believe you have a rework planned for the radiation system, so it's entirely possible this is irrelevant to mention, but I figured it never hurts to file a report. Thank you for all the effort you've put into this mod; I look forward to seeing how it continues!

**Comment by zOnlyKroks** [comment]
This could be fixed by internally using a long, i can maybe attempt this soon ish
