### ISSUE TITLE
Death by endless radiation even with no radiation around.

### ISSUE THREAD

**Issue by border999** [igentuman/NuclearCraft-Neoteric#135]
NuclearCraft-1.20.1-1.1.0-rc.1 - dummmmmmy-1.20-2.0.2
(https://gist.github.com/border999/8a727938a9ca79cd345660b9177e7a99)

**Comment by magnusa2007** [comment]
Happend to me too
NuclearCraft-1.20.1-1.1.0-rc.1 + 236 mods

And on new pack with only nuclearcraft

**Comment by LiamThomp** [comment]
Yeah, I'm not sure this is fixable through configs, unless we turn off Radiation completely.
