### ISSUE TITLE
Fusion reactor

### ISSUE THREAD

**Issue by igentuman** [igentuman/NuclearCraft-Neoteric#18]
- [x] Rf amplifiers
- [x] Electromagnets
- [x] Casing
- [x] Core
- [x] Connectors 

### Gameplay
Player has to control reactor parameters in order to get maximum energy from reactor.
In order reactor to run it must:

- have fuel, 
- charged functional parts 
- enough energy for functional blocks, 
- functional blocks need to be cooled.

### Functional blocks:
Electromagnets - used to control plasma stability. Better stability - better efficiency, less casing and functional blocks heat per tick.
RF Amplifiers - used to increase plasma temperature. Each recipe has optimal plasma temperature for better energy generation.

Player has to place several electromagnets and rf amplifiers around toroid. each toroid side must have at least 1 magnet and rf amplifier.

Each functional block has energy requirements, heat generation and max heat cap.
To cooldown functional blocks, coolant fluid need to be supplied into reactor core.

Reactor GUI gives player possibility to control energy for rf amplifiers.
And by that player can adjust plasma heat gain. It also affects heat generation.

Plasma temperature might have some deviations on low level of plasma stability.

### The flow

1. Add some fuel
2. Add coolant
3. Plug input energy to charge functional blocks
4. Adjust RF Amplifiers power %
5. Run reactor

On early stage it would be better to set rf amplifiers power to 100%.
As soon as plasma gets optimal temperature player will have to adjust rf amplifiers power % to keep temperature near desired value as close as possible.

States of reactor

- incomplete - structure validation not passed
- stand by - reactor is valid but not running 
- generating - has fuel, inner energy, coolant and redstone signal. Processing fusion recipe
- meltdown - casing/functional blocks overheat

**Comment by joendter** [comment]
how is the temperature loss per tick calculated?
