### ISSUE TITLE
Item Data Issue

### ISSUE THREAD

**Issue by Samrel556** [igentuman/NuclearCraft-Neoteric#23]
When a block is placed in the world then broken it appears to get new data which makes it incapable of stacking with unplaced blocks in the inventory.

To Reproduce:
1. Create new world with only JEI and Nuclearcraft installed
2. Creatively give yourself placeable blocks
3. Place blocks
3. Break blocks in Survival
4. Notice items no longer stack with original stack

Issue Persists even when Nuclearcraft is removed from game

**Comment by igentuman** [comment]
What kind of blocks?
