### ISSUE TITLE
[BUG] java.lang.NullPointerException on parsing custom recipes with kubejs -> custom recipes with NC types not work

### ISSUE THREAD

**Issue by DevDyna** [igentuman/NuclearCraft-Neoteric#24]
I have literally to try to copy-paste the json recipe and on both (kubejs and vanilla datapacks) don't work 
(vanilla version didn't have sended nothing on log , kubejs sended java.lang.NullPointerException on parsing the recipe)

directory : <modpack>/kubejs/data/nuclearcraft/recipes/name.json
```
{
  "type": "nuclearcraft:alloy_smelter",
  "input": [
    {
      "tag": "forge:dusts/boron"
    },
    {
      "tag": "forge:dusts/steel"
    }
  ],
  "output": [
    {
      "count": 2,
      "item": "nuclearcraft:ferroboron_ingot"
    }
  ],
  "powerModifier": 1.0,
  "radiation": 1.0,
  "timeModifier": 1.0
}
```
kubejs method:
directory : kubejs/server_scripts/recipes/nuclearcraft/fluid_infuser.js

```
event.custom({
  "type": "nuclearcraft:alloy_smelter",
  "input": [
    {
      "tag": "forge:dusts/boron"
    },
    {
      "tag": "forge:dusts/steel"
    }
  ],
  "output": [
    {
      "count": 2,
      "item": "nuclearcraft:ferroboron_ingot"
    }
  ],
  "powerModifier": 1.0,
  "radiation": 1.0,
  "timeModifier": 1.0
})
```

[logs are a bit long due counter on game]
[latest.log](https://github.com/igentuman/NuclearCraft-Neoteric/files/13230624/latest.log)

kubejs server log:
[server.log](https://github.com/igentuman/NuclearCraft-Neoteric/files/13230790/server.log)

**Comment by igentuman** [comment]
Yeah. Confirming that. But i have no idea how to fix that

**Comment by igentuman** [comment]
Alright. I figured out what you need to put datapack.zip into datapack subfolder of save folder

MyWorld/datapack/datapack.zip
And it works.

Kubejs have less priority for me atm. So will check that later

**Comment by igentuman** [comment]
[test.zip](https://github.com/igentuman/NuclearCraft-Neoteric/files/13260836/test.zip)

**Comment by DevDyna** [comment]
It work except that if reloaded one more time it keep the old recipe
and all recipes with custom types cannot be removed/modified without override one by one

**Comment by DevDyna** [comment]
/saves/*world*/datapacks/*folder*/data/nuclearcraft/recipes/alloy_smelter/*name*.json
```
{
  "type": "nuclearcraft:alloy_smelter",
  "input": [
    {
      "tag": "forge:dusts/copper"
    },
    {
      "tag": "forge:dusts/iron"
    }
  ],
  "output": [
    {
      "count": 3,
      "item": "nuclearcraft:ferroboron_ingot"
    }
  ],
  "powerModifier": 1.0,
  "radiation": 1.0,
  "timeModifier": 1.0
}
```
`copper` + `iron`
On game:
![image](https://github.com/igentuman/NuclearCraft-Neoteric/assets/78147916/8b363c41-f004-4938-833e-d777b1e3ca54)
where `iron` still `steel` (old recipe changed before a /reload)
if reloaded more times keep on still without update , same if closed and reopened the world
