### ISSUE TITLE
Depleted fuel icon appears when fuel pellet is added to the fission reactor

### ISSUE THREAD

**Issue by CommanderAva** [igentuman/NuclearCraft-Neoteric#28]
I've loaded one LEU-235 pellet into the reactor I've built.
The power generation started. Depleted fuel pellet icon appears in the used fuel slot; however, it is not possible to pick it up and pellet actually appears only after it is depleted by reactor process.

STR:
Add LEU-235 fuel pellet into the reactor fuel slot and activate the reactor
ER: Reaction starts, once the loaded fuel is used up a pellet of depleted fuel appears
AR: Depleted fuel pellet icon appears immidiately after start and remains there untill the control block is broken.
![s2](https://github.com/igentuman/NuclearCraft-Neoteric/assets/30376628/04c76735-ec32-4211-851f-798e114d8c75)
Issue reproduced on artifact available from this action:
https://github.com/igentuman/NuclearCraft-Neoteric/actions/runs/7028062608

**Comment by CommanderAva** [comment]
The issue appears to be a bit different - will update this bug after some additional testing

**Comment by igentuman** [comment]
This is actually a feature i mean to make))
