### ISSUE TITLE
[BUG] java.lang.RuntimeException: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER

### ISSUE THREAD

**Issue by TheTroQ** [igentuman/NuclearCraft-Neoteric#36]
When trying to break a block in survival on dedicated server using the lastest artifact jar from github (occures on 1.0 release form curseforge too) with no other mods on 1.19.2 the block doesn't drop and the console log produces this output :
https://nekobin.com/yizovewiwa

**Comment by igentuman** [comment]
Try this build
https://github.com/igentuman/NuclearCraft-Neoteric/actions/runs/7211326562
