### ISSUE TITLE
Version Update

### ISSUE THREAD

**Issue by Ceifeire** [igentuman/NuclearCraft-Neoteric#39]
Hi,

I just updated a world from Alpha 6 to the latest released version 1.0.1. Have run into an issue with the fission reactor blocks not behaving correctly. If i try to break them they disappear for a sec and then respawn and act present. The controller is still interactable but if i use it it behaves as if there are no heat sinks inside.

How can I correct this? Everything else appears to be working fine.

**Comment by Ceifeire** [comment]
Did a solo test and got the same result with the fission reactor. The heat/energy numbesr are not matching the description. Using Uranium heu-235 i was getting 14600h/t instead of 1200h/t with 4 fuel cells.

**Comment by igentuman** [comment]
Could you please check this design in plannerator?

**Comment by Ceifeire** [comment]
yeah im seeing the same numbers in this planner as i was seeing in game. but i get a different result when using the alpha 6 version. Was there an overhaul in how heat and power work with fission reactors?

I have attached the png below.
![HEU-235 3 x 3 x 3](https://github.com/igentuman/NuclearCraft-Neoteric/assets/38624271/0702292f-d755-49e4-b28e-15f9788e75d7)

**Comment by Ceifeire** [comment]
also just tried placing the active cooler but found out it has no recipe and it causes the game to crash when trying to place in a reactor.

Crash report below

https://pastebin.com/2uF91nv8
