### ISSUE TITLE
One recipe breaks KubeJS i think ?

### ISSUE THREAD

**Issue by Leclowndu93150** [igentuman/NuclearCraft-Neoteric#40]
https://gnomebot.dev/paste/1187447442363387934

**Comment by Leclowndu93150** [comment]
hey do u mind giving me a build so i can continue working on my modpack please ?

**Comment by Leclowndu93150** [comment]
@igentuman

**Comment by igentuman** [comment]
@Leclowndu93150  checkout latest build

**Comment by Leclowndu93150** [comment]
> @Leclowndu93150 checkout latest build

im about to try it thanks !

**Comment by Leclowndu93150** [comment]
heh i forgot to tell you that it was on 1.20.1 too

**Comment by igentuman** [comment]
i'm doing fixes in 1.19 branch no. all these fixes will go to 1.20 in one merge later

**Comment by Leclowndu93150** [comment]
hey its been a month, will we have a 1.20.1 build please ?
