### ISSUE TITLE
Sound Error

### ISSUE THREAD

**Issue by Ceifeire** [igentuman/NuclearCraft-Neoteric#42]
Hi,

We are playing on a dedicated server and just updated to the latest version 1.0.2. After playing for a while I logged off near my fission reactor and have not been able to load into the server since. The whole game crashes trying to connect to the server. The crash report is below. It claims there is a sound reporting null from the fission reactor controller as far as I can tell.

I am the only one experiencing this issue so I am not sure if it can be reproduced.

https://pastebin.com/GPCRzqYf

**Comment by igentuman** [comment]
Please tryout latest build
