### ISSUE TITLE
DecoderException issue (when using the mod in Forge server 1.20.1 with Forge version 47.2.16)

### ISSUE THREAD

**Issue by FalkenFal** [igentuman/NuclearCraft-Neoteric#43]
it's fine when i use it in a singleplayer world, but when i try to join my forge server this error occur

![image](https://github.com/igentuman/NuclearCraft-Neoteric/assets/154776648/0958bb1e-5056-4dd2-a0d9-f6c60883521a)

**Comment by igentuman** [comment]
Fixed in 1.19 branch. Need to merge
