### ISSUE TITLE
Fission Reactor Does not Generate, Output Power

### ISSUE THREAD

**Issue by ImperialsGit** [igentuman/NuclearCraft-Neoteric#52]
Reactor plan is as follows:
<img width="710" alt="image" src="https://github.com/igentuman/NuclearCraft-Neoteric/assets/68413525/0f0ee3a2-636d-4ea6-a91b-d0122993a2c9">
(I know it's bad we don't need to talk about it)

Fuel used was Thorium TBU Oxide, heat was created but no power was generated. Ran on latest artifact version. In addition, I couldn't find any way to output power with mekanism pipes, neither from the controller or reactor ports.

Also, active heat sinks don't seem to impact the cooling value of the fission reactor, or at least that active heat sinks won't be fed by ports when placed in direct contact with them.

**Comment by igentuman** [comment]
show gui screenshots pls

**Comment by ImperialsGit** [comment]
My bad. Last image has my cursor over the the middle bar.
![2024-01-04_02 37 07](https://github.com/igentuman/NuclearCraft-Neoteric/assets/68413525/b630ee7a-374c-4588-a868-dc6b591b311e)
![2024-01-04_02 37 02](https://github.com/igentuman/NuclearCraft-Neoteric/assets/68413525/a6b93c12-99b1-4a6a-b3e2-ecf7c0530a92)
![2024-01-04_02 37 20](https://github.com/igentuman/NuclearCraft-Neoteric/assets/68413525/80f197d4-7450-4c28-9e60-c24987bec6cb)

**Comment by igentuman** [comment]
This is odd. According to 3 bars on screenshot you have boiling mode enabled. But where is the button? There must be a button above checkboxes

**Comment by ImperialsGit** [comment]
I've tried disabling all the UI mods I can, disabling shaders and resourcepacks as well, but the button will not show up, though it is interactable. Modlist is as follows:
[modlist.txt](https://github.com/igentuman/NuclearCraft-Neoteric/files/13835871/modlist.txt)

Also, while switching it to power mode did make it start generating power, the ports I have for active coolers no longer connect with fluid pipes. Am I using the wrong block for this?

**Comment by igentuman** [comment]
Active cooler is not implemented yet and it shouldn't have a recipe for now.
Fluid pipes can only be connected in boiling mode
