### ISSUE TITLE
NuclearCraft doesn't let me join server

### ISSUE THREAD

**Issue by Riiswalker** [igentuman/NuclearCraft-Neoteric#55]
**Situation:**
I'm making a modpack for my friends and myself. To test everything I set up a local server which won't let me join with Nuclearcraft Neoteric installed (works without). Could be a mod incompatibility or smth but i dont know.
![javaw_62tAQPulLc](https://github.com/igentuman/NuclearCraft-Neoteric/assets/157012463/7370da6a-785d-42ed-8b9a-fd8be0bbd0f6)
I also tried to remove the mod mentioned, but keep getting the same issue with other mods (and same message but different mod mentioned)
![javaw_Y78RB9hqzx](https://github.com/igentuman/NuclearCraft-Neoteric/assets/157012463/3dbc2b3e-e75f-49da-9d41-bea3907b66b3)
Only removing NuclearCraft though works.

**Logs:**
**Server:** Server isn't crashing so no crashlog and normal logs wont show anything except me disconnecting after trying to join.

**Client:** 
Client didn't generate any Crashlogs

[latest.log](https://github.com/igentuman/NuclearCraft-Neoteric/files/13975467/latest.log)

Edit:
I use NuclearCraft-1.20.1-1.0.0-beta.1 with Minecraft 1.20.1 Forge 47.2.19 in my modpack
with these mods 
[mods.txt](https://github.com/igentuman/NuclearCraft-Neoteric/files/13975550/mods.txt)

**Comment by igentuman** [comment]
known issue. fixed in 1.19 branch. waiting to merge into 1.20 branch
