### ISSUE TITLE
Config resets when launching the game

### ISSUE THREAD

**Issue by entropySingularity** [igentuman/NuclearCraft-Neoteric#57]
When launching the game with modified nuclearcraft-common.toml, the file reverts to default settings and a .bak file is created in the config folder.
Tested on: 1.19.2-1.0.2 and 1.20.1-1.0.0-beta.1

There is a warning suggesting the file is invalid:
[21:51:19] [Thread-2/WARN] [ne.mi.fm.co.ConfigFileTypeHandler/CONFIG]: Configuration file /home/user/.local/share/multimc/instances/nuclearcraft/.minecraft/config/nuclearcraft-common.toml is not correct. Correcting
but this occurs with every change to the config (I tested changing processor_time for the rock crusher from 200 to 190 and setting in_situ_leaching enable_veins to false).

**Comment by igentuman** [comment]
Yes i know it. This is why i going to rework config
https://github.com/igentuman/NuclearCraft-Neoteric/issues/54
