### ISSUE TITLE
[Bug] Override of custom type recipes to replace/remove require restart the game

### ISSUE THREAD

**Issue by DevDyna** [igentuman/NuclearCraft-Neoteric#58]
Mod version : 1.19.2 1.0.2
Description:
I'm try to override some recipes to remove them so i wrote a empty json with same directory and name as recipe id like that

![image](https://github.com/igentuman/NuclearCraft-Neoteric/assets/78147916/ad0a6019-a83d-43a5-9638-e376f2b71309)

so i place on the folder [using kubejs as datapack folder] on `data\nuclearcraft\recipes\alloy_smelter` as `dusts_tin-dusts_silver.json` with content  ```{}```  , reloaded with /reload but keep on persist

also i have already try using kubejs or other methods but keep on persist (included if used with vanilla datapacks)
## Solution to temp-fix:
restart the game and the recipe vanish

**Comment by igentuman** [comment]
Solved
