### ISSUE TITLE
KubeJS issue still not fixed

### ISSUE THREAD

**Issue by Leclowndu93150** [igentuman/NuclearCraft-Neoteric#60]
[server.log](https://github.com/igentuman/NuclearCraft-Neoteric/files/14151461/server.log)
maybe something is wrong with my instance

**Comment by KSPAtlas** [comment]
Hey i figured out the issue, NuclearCraft Neoteric breaks the event.remove() method of  ServerEvents.recipes, which will only work when using an "id" type to remove the recipe.

**Comment by igentuman** [comment]
What the hell? You won't find any mentions of ServerEvents in Nuclearcraft? How it suppose to be broken by NC?

**Comment by KSPAtlas** [comment]
@igentuman idk either, but i know it happens
