### ISSUE TITLE
NC breaks radiation from Mekanism

### ISSUE THREAD

**Issue by marcin212** [igentuman/NuclearCraft-Neoteric#62]
The value on the dosimeter from Mekanism does not increase. The player does not receive damage. The Geiger counter (with Mekanism) shows the correct value. The radiation exposure on the screen is 305mSv because I turned on the modpack for a while without NC

![obraz](https://github.com/igentuman/NuclearCraft-Neoteric/assets/3790635/608c78d7-eaff-4d78-b219-afc2b3041d6b)

Mods: 
cc-tweaked-1.20.1-forge-1.109.4
Mekanism-1.20.1-10.4.5.19
MekanismGenerators-1.20.1-10.4.5.19
NuclearCraft-1.20.1-1.0.0-beta.2

forge - 47.2.19
mc - 1.20.1

**Comment by igentuman** [comment]
Have you tried on NC 1.19? It has to work on increasing radiation. Not decreasing

**Comment by marcin212** [comment]
I created a modpack on the fly to test 1.19. Same problem:
![obraz](https://github.com/igentuman/NuclearCraft-Neoteric/assets/3790635/fffe055c-7e2f-4ef3-8055-b6d26e41de4f)
![obraz](https://github.com/igentuman/NuclearCraft-Neoteric/assets/3790635/2cba1235-245a-4f73-9ae8-c71444aebef1)
