### ISSUE TITLE
[Bug] Recipe stuck and never want end up

### ISSUE THREAD

**Issue by DevDyna** [igentuman/NuclearCraft-Neoteric#63]
I have insered on manufactory a graphite ingot to make graphite dust and lefted it inside , after a few of minutes reopened the gui and still broken
I'm here at waiting for more that 10 minutes but still same
The machine have power but dont use it

![2024-02-21_13 38 55](https://github.com/igentuman/NuclearCraft-Neoteric/assets/78147916/cd085f05-3fbf-410c-b862-5782c38d6332)

[20 minutes later after broken energy cable below it]

![2024-02-21_13 47 06](https://github.com/igentuman/NuclearCraft-Neoteric/assets/78147916/307d70fb-e2e5-405f-8507-74c33ce61e44)

same if broken and placed on another location

![2024-02-21_13 56 44](https://github.com/igentuman/NuclearCraft-Neoteric/assets/78147916/5591cb42-c8c1-401c-b808-1589db57b07a)
 
using `/data` command to see inside (maybe can be useful)

![2024-02-21_13 58 13](https://github.com/igentuman/NuclearCraft-Neoteric/assets/78147916/149aaea0-d4de-43f3-a637-243ded5d770e)

![2024-02-21_13 59 57](https://github.com/igentuman/NuclearCraft-Neoteric/assets/78147916/4f03ba36-0d93-4205-80e0-a24aff4da1fd)

also persist if closed the world

mod version : NuclearCraft-1.20.1-1.0.0-beta.2
forge : 47.2.0
modlist : [ForgePlay-0.zip](https://github.com/igentuman/NuclearCraft-Neoteric/files/14359691/ForgePlay-0.zip)

[latest.log](https://github.com/igentuman/NuclearCraft-Neoteric/files/14359776/latest.log)

**Comment by igentuman** [comment]
Many weird stuff is happening in the log

why we have so many lines like this one?
[12:32:14] [Server thread/ERROR]: Failed to scan recipe nuclearcraft:manufactory/ingots_graphite. This should be reported to nuclearcraft!
java.lang.IllegalStateException: Recipe getResultItem is null

**Comment by igentuman** [comment]
Like it says current recipe is nuclearcraft:manufactory/ingots_graphite but as we can see, it has null result Item

**Comment by DevDyna** [comment]
> why we have so many lines like this one? [12:32:14] [Server thread/ERROR]: Failed to scan recipe nuclearcraft:manufactory/ingots_graphite. This should be reported to nuclearcraft!

ehm lol , i literally installed some mods without change nothing and i didn't expected that happen

**Comment by DevDyna** [comment]
also it's strange due i have crafted some graphite dust before this happen with same way

**Comment by igentuman** [comment]
we  need to figure out the proper steps how to reproduce

**Comment by DevDyna** [comment]
> we need to figure out the proper steps how to reproduce

mh.. probably quark cause this or zeta
also a few of days before [quark send same client on crash](https://github.com/VazkiiMods/Quark/issues/4678) so maybe zeta have corrupted all NC recipes?

i have reopened the same world and some recipes work on world and on jei but recipe button dont send nothing -> probably caused by same issue

after that i have try on a testing world and all recipes on jei still missing (NC only) but all recipes on machines still "alive"

**Comment by igentuman** [comment]
We need to keep an eye on this. Will return to that after i re-work recipes serializer. I need to implement tag outputs.

**Comment by DevDyna** [comment]
> also a few of days before https://github.com/VazkiiMods/Quark/issues/4678 so maybe zeta have corrupted all NC recipes?

happen again with another manufactory so wansn't caused on recent client crash for quark due i have crafted yesterday this manufactory and the crash was before

![2024-02-22_20 09 25](https://github.com/igentuman/NuclearCraft-Neoteric/assets/78147916/44fd5248-6fd4-4c31-bd9d-d507b2a6f534)

**Comment by DevDyna** [comment]
apparently with NuclearCraft-1.20.1-1.0.0-beta.3 , it look fixed (on log dont send thousand of recipe errors about NC)
