### ISSUE TITLE
Disabling oregen breaks the GT ore prospector

### ISSUE THREAD

**Issue by ThePansmith** [igentuman/NuclearCraft-Neoteric#66]
![image](https://github.com/igentuman/NuclearCraft-Neoteric/assets/70342772/627619ca-f697-426e-8a94-8bc8c85047f1)
On 1.20, latest version of NCN. Disabling NCN's oregeneration will cause the Gregtech ore prospector to freak out and not render properly, not showing any ores at all. I think the ores themselves don't generate, though.

**Comment by igentuman** [comment]
Some details maybe? Version at least

**Comment by ThePansmith** [comment]
Updated

**Comment by igentuman** [comment]
Did you disabled ore registration or changed vein size to 0?

**Comment by Leclowndu93150** [comment]
> Did you disabled ore registration or changed vein size to 0?

looks like ore registration
![image](https://github.com/igentuman/NuclearCraft-Neoteric/assets/73310949/79850995-051d-4d30-8ddd-e9837f281738)

**Comment by ThePansmith** [comment]
Setting vein size to zero or using kjs doesn't seem to affect anything, and disabling the ore causes the issue.
