### ISSUE TITLE
Energy upgrades not working in [ALL]

### ISSUE THREAD

**Issue by Michepoli** [igentuman/NuclearCraft-Neoteric#71]
I added a recipe to the assembler and with 64 speed upgrades it costed 1.3k rf/t even if the machine showed 26k rf/t; adding energy upgrades changed nothing to the cost, it only increased with speed ones.
Energy cost with 0 upgrades (remains the same with just energy upgrades)
![immagine](https://github.com/igentuman/NuclearCraft-Neoteric/assets/159149393/a7c82328-3459-494c-a36c-bbbef6dab27a)
Energy cost with 64 speed upgrades (remains the same with energy upgrades of any number)
![immagine](https://github.com/igentuman/NuclearCraft-Neoteric/assets/159149393/0ae2575b-c35c-4f0a-93c5-922421f7e2bc)

**Comment by igentuman** [comment]
Ok. This touches all versions.

**Comment by igentuman** [comment]
Fixed in 1.19, 1.20

**Comment by igentuman** [comment]
fixed in 1.18

**Comment by Xplodin** [comment]
This issue seems to have come back in 1.20.1 

<img width="510" height="254" alt="Image" src="https://github.com/user-attachments/assets/114f7e69-6134-4d28-8af3-9ce7691247d9" />
