### ISSUE TITLE
[1.20.1] Side Configuration does not seem to work.

### ISSUE THREAD

**Issue by FrozenGalaxy** [igentuman/NuclearCraft-Neoteric#72]
I tried clicking the colored boxes in the GUI, nothing happens.
See video:

https://github.com/igentuman/NuclearCraft-Neoteric/assets/156858866/df23e7d2-a6fe-439b-b718-7f2514e09d68

EDIT:
also the background of the text is mis aligned:
![image](https://github.com/igentuman/NuclearCraft-Neoteric/assets/156858866/6e3e758d-c1c8-4e6d-b452-eecbefcd0930)

**Comment by igentuman** [comment]
what version of the mod?

**Comment by FrozenGalaxy** [comment]
NuclearCraft-1.20.1-1.0.0-beta.5.jar

**Comment by igentuman** [comment]
I can't confirm that. It looks like you use an old version
I remember i fixed that already. Checkout latest 1.20 build from github
![image](https://github.com/igentuman/NuclearCraft-Neoteric/assets/4759881/8042c936-fb47-4aac-91a7-2388d8bee55a)

**Comment by FrozenGalaxy** [comment]
I am using the latest forge version, but ill try it with a github master build
