### ISSUE TITLE
[1.20.1] Fission reactor port redstone mode is incorrectly rendered

### ISSUE THREAD

**Issue by marcin212** [igentuman/NuclearCraft-Neoteric#75]
Mod Versions:

    NuclearCraft-1.20.1-1.0.0-beta.5.jar
    Forge 47.2.19

![obraz](https://github.com/igentuman/NuclearCraft-Neoteric/assets/3790635/704611a3-67cf-45f5-ac5e-21daa236c196)

**Comment by igentuman** [comment]
I was not able to reproduce it
