### ISSUE TITLE
[1.20.1] Depleted Fuels don't show in JEI

### ISSUE THREAD

**Issue by Leclowndu93150** [igentuman/NuclearCraft-Neoteric#76]
![image](https://github.com/igentuman/NuclearCraft-Neoteric/assets/73310949/7e5e988a-ffcf-403c-81e6-6c8c69a488d0)

maybe a bunch of other things don't show either

**Comment by igentuman** [comment]
duplicate of Depleted Fuels do not appear in JEI #70
