### ISSUE TITLE
Fission Reactor Glass not TRANSPARENT when block placed

### ISSUE THREAD

**Issue by ZTagre** [igentuman/NuclearCraft-Neoteric#78]
To begin, let me say I love the mod, and I'm very glad you have chosen to bring it back from the "dead"! Also, I am aware that my version of MC is an older supported version, 1.18.2; still, maybe you could look into a few things that really should be fixed, as they are killer problems!

   1) The Fission Reactor Glass appears normal when it is rendered in the inventory, but when the block is placed, it looks like white cloudy glass, totally opaque (yeah, you can't see through it at all...).

   2) Both the Fission Reactor Casing AND the Fission Reactor Glass can't be broken, even with "silk touch" tools! They both completely disappear afterwards, so you better place those blocks correctly the VERY FIRST TIME! Yeah right :-}

   Again, I know I play on an older version of MC, and if I had known ahead of time about the possible problems I would have with THIS MOD, I might have gone with a newer version! But I already have a world very far developed, and I'm not wanting to change versions just yet...

   Please, just have a quick look, and see if the fixes might not be too hard? The rest (if any) I think I can "live with"!

   Thanks in advance for hearing me out, and for considering these issues for a older (but still VERY POPULAR) version!

   Big Fan;
     ZTagre

**Comment by igentuman** [comment]
Will check that out

**Comment by igentuman** [comment]
![image](https://github.com/igentuman/NuclearCraft-Neoteric/assets/4759881/284a1ccf-c0b4-4fab-be9d-d2d181a2c296)

**Comment by igentuman** [comment]
Loot tables are broken
