### ISSUE TITLE
No way to void fluid [1.19]

### ISSUE THREAD

**Issue by xWaller0119** [igentuman/NuclearCraft-Neoteric#79]
There's no way to void fluid in the input sides if you put the wrong thing in, so you kinda have to just make a whole new machine... :(

**Comment by igentuman** [comment]
What version?

**Comment by FittingCanvas** [comment]
Not sure what this guy is playing on, but as you already know, this happened to me. (Most Recent [1.19.2] Release)

**Comment by igentuman** [comment]
Just tested on current 1.19 build. SHIFT+ mouse 1, as intended
