### ISSUE TITLE
Melter gives random outputs given random items

### ISSUE THREAD

**Issue by TheTroQ** [igentuman/NuclearCraft-Neoteric#81]
As shown below in this instance bedrock gives Curium and there is no recipe for other liquid 
Each time the game is restarted the missing recipes randomizes

![image](https://github.com/igentuman/NuclearCraft-Neoteric/assets/39279124/fdbbd87a-026a-46d6-8ad6-69216aac6930)
![image](https://github.com/igentuman/NuclearCraft-Neoteric/assets/39279124/31b47d0e-30ba-4da3-8c6f-d277b1e9bb9f)

**Comment by igentuman** [comment]
can't confirm that

**Comment by igentuman** [comment]
![image](https://github.com/igentuman/NuclearCraft-Neoteric/assets/4759881/30aa708d-4b89-4c4e-8e68-45341fcb879b)
