### ISSUE TITLE
KUBEJS Compatibility issues

### ISSUE THREAD

**Issue by TheTroQ** [igentuman/NuclearCraft-Neoteric#82]
As mentioned in issue #81 i managed to narrow it down to a reproducable example

When adding any recipe modification to the game with kubejs nuclear craft reicpes got broken for example melter 

Example:

> ServerEvents.recipes((e) => {
>     e.remove({output: 'ender_eye'})
> })

removes the ender eye reicpe as expected but in a side effects makes minecraft:air as a vaild input (as shown in REI) causing aby block to produce fluid as shown below:
![image](https://github.com/igentuman/NuclearCraft-Neoteric/assets/39279124/1ed1def0-4643-4923-a3d2-f1649e42e333)

Adding item craftings gives simillar outcome 

Mods used to produce this output:
architectury-9.2.14-forge
kubejs-forge-2001.6.4-build.138
NuclearCraft-1.20.1-1.0.0-beta.6 (compiled form lastest github version)
rhino-forge-2001.2.2-build.18

**Comment by igentuman** [comment]
Disabling ores issues https://github.com/igentuman/NuclearCraft-Neoteric/issues/66

**Comment by Leclowndu93150** [comment]
your KubeJS compat is cursed dude

**Comment by igentuman** [comment]
@Leclowndu93150 kubejs is fucking garbage

**Comment by MadSciSlack** [comment]
> @Leclowndu93150 kubejs is fucking garbage

Garbage or not, it's still the best tool available for making scripted changes for modpack makers.  We still need it to work, so maybe try being helpful instead of being a twat.  If pack makers can't work with your stuff, you're doing something wrong.

I've been working on a modpack with voice content and 650 quests for 18 months.  Your response here has just ensured that this mod won't be in it.  I liked this mod, but I won't be supporting it since this is your attitude.

**Comment by igentuman** [comment]
> > @Leclowndu93150 kubejs is fucking garbage
> 
> Garbage or not, it's still the best tool available for making scripted changes for modpack makers. We still need it to work, so maybe try being helpful instead of being a twat. If pack makers can't work with your stuff, you're doing something wrong.
> 
> I've been working on a modpack with voice content and 650 quests for 18 months. Your response here has just ensured that this mod won't be in it. I liked this mod, but I won't be supporting it since this is your attitude.

As you can see i already attempted to fix kubejs compat several times. And i have my reasons to hate it. I made NC in best practice as it offered by forge guides. But kubejs messing things around.
