### ISSUE TITLE
Could you consider compatibility with TFC:TNG?

### ISSUE THREAD

**Issue by wglpython** [igentuman/NuclearCraft-Neoteric#83]
pls,i like the mod very much

**Comment by igentuman** [comment]
Sorry mate. I have no idea of what the heck are you asking about. You don't even try to spend couple minutes to prepare proper description. So why would i spend hours on that?

**Comment by wglpython** [comment]
> Sorry mate. I have no idea of what the heck are you asking about. You don't even try to spend couple minutes to prepare proper description. So why would i spend hours on that?

oh sry, I mean is, is it possible to have the mineral generation from NuclearCraft in the world of TFC:TNG? However, I have already solved this issue. I'm really sorry about that.
