### ISSUE TITLE
1.18.2 Bugs (One large one, and one small one)

### ISSUE THREAD

**Issue by nohax955** [igentuman/NuclearCraft-Neoteric#87]
there is a huge bug in 1.18.2
it just causes crashes instantly
it happens with the nuclear furnace
if u click open recipes in it
it just crashes your game
also it seems the nuclear furnace doesnt have a purpose as if u try to view what it can do in jei it doesnt show anything
also when the fission reactor blows up there is 5 columns of the white stuff that extends from the top of the reactor to the height limit

**Comment by igentuman** [comment]
Nuclear furnace is not implemented yet. Does it have a recipe?

**Comment by nohax955** [comment]
yes

**Comment by nohax955** [comment]
> Nuclear furnace is not implemented yet. Does it have a recipe?

yes
bib
ifi
bib
b=basic plate
f=furnace
i=iron ingot
