### ISSUE TITLE
The mod cannot be used on the server. [1.18]

### ISSUE THREAD

**Issue by wglpython** [igentuman/NuclearCraft-Neoteric#90]
"Internal Exception: io.netty.handler.codec.EncoderException: java. lang.IllegalArgumentException: unable to fit 2122030 into 3"
My technical team and I have checked the logs, but it seems that we haven't identified where the error occurred. I can only confirm that the error is caused by NC.
[latest.log](https://github.com/igentuman/NuclearCraft-Neoteric/files/14969985/latest.log)

**Comment by fengshuo2004** [comment]
你遇到的问题是服务端崩溃，不是客户端对吧？你发的 `latest.log` 是客户端的 log。我们要看服务端的 log 才能知道问题出在哪里。

So you are experiencing server crash, not client crash right? The `latest.log` file you provided is a client-side log file. We need to see the server-side log to know what the problem is.

**Comment by wglpython** [comment]
> 你遇到的问题是服务端崩溃，不是客户端对吧？你发的 是客户端的 log。我们要看服务端的 log 才能知道问题出在哪里。`latest.log`
> 
> So you are experiencing server crash, not client crash right? The file you provided is a client-side log file. We need to see the server-side log to know what the problem is.`latest.log`

ok
[log.txt](https://github.com/igentuman/NuclearCraft-Neoteric/files/14981303/log.txt)

**Comment by wglpython** [comment]
![5Y)U XNGJ6JB%F`$ NXU1@E](https://github.com/igentuman/NuclearCraft-Neoteric/assets/153580345/ebda4e32-250e-4635-8009-6fe4e2fb0ac5)
@igentuman I tried using Packet Fixer on the server to make NuclearCraft work, but encountered a new issue. There are no error messages in the logs.

**Comment by igentuman** [comment]
Just tried on latest build. Everything is working.

**Comment by igentuman** [comment]
This is not related to NC. Tested on current build. And logs are not pointing to NC
