### ISSUE TITLE
Turbine Port crashes the game [1.19.2]

### ISSUE THREAD

**Issue by DexxKnight1** [igentuman/NuclearCraft-Neoteric#96]
Minecraft version: 1.19.2
NuclearCraft: Neoteric version: 1.0.3
----------------------------------------------
By clicking on a Turbine Port the game crashes. Seems that has some rendering issues with the FancyMenu mod (I've tested on couple FancyMenu version)

[crash-2024-05-01_12.06.12-client.txt](https://github.com/igentuman/NuclearCraft-Neoteric/files/15176184/crash-2024-05-01_12.06.12-client.txt)

**Comment by igentuman** [comment]
Turbine is not implemented yet
